name: contrastive-cae
channels:
  - defaults
dependencies:
  - tqdm
  - matplotlib
  - scipy
  - scikit-learn
  - scikit-image
  - pip
  - pip:
    - wandb
    - torch
    - einops
    - argparse
    - pycocotools
    - torchvision