name: cae-contrastive
channels:
  - defaults
dependencies:
  - torchvision
  - pytorch
  - tqdm
  - matplotlib
  - scipy
  - scikit-learn
  - scikit-image
  - pip:
    - einops
    - wandb
    - torchmetrics
    - argparse
    - pycocotools